### ISSUE TITLE
Testing different types

### ISSUE THREAD

**Issue by terryr1** [Danijj89/CS4500-A1-Part2#14]
There should be tests for bool, integer, and float arrays in addition to string.

**Comment by Danijj89** [comment]
What kind of implementation of typed arrays would you like me to test? Do you have something on the line of IntArray, BoolArray etc, or are you wrapping the primitives? Since I don't have classes for them, I'm not sure how to write the tests.

**Comment by terryr1** [comment]
Yeah we have IntArray, BoolArray, and FloatArray so that would be fine. You can just do it exactly like the string ones but use the other types. We used primitives in each of the arrays other than the String array. Thanks

**Comment by Danijj89** [comment]
Sounds good. Will try to push it asap.

**Comment by Danijj89** [comment]
Do we need to add specs for those typed arrays as well?

**Comment by Danijj89** [comment]
What class does your typed array extend?

**Comment by terryr1** [comment]
It extends Object, I don't think you need to add specs for the typed array but I'm not sure

**Comment by Danijj89** [comment]
Updated tests, let me know if there are any issues. Thanks
