### ISSUE TITLE
Remove nullptr return checks on get()/set() associated Array tests

### ISSUE THREAD

**Issue by aperez809** [Danijj89/CS4500-A1-Part2#15]
In your API spec, the `get()` and `set()` methods return a `nullptr` if the provided index is out of bounds (i.e. < 0 or >= list's length). This approach works for String and Object Arrays but for Float, Int, and BoolArrays, it creates a return type mismatch. That is, if the method declaration is 
```
bool get(size_t i) { ... }
``` 
a `nullptr` cannot be returned because it is not of type `bool`. Listed below are links to lines in which your tests check for these kinds of cases. We are requesting that you remove them, as we will be checking these cases with assert statements, which would cause the test suites to stop running prematurely. 

https://github.com/Danijj89/CS4500-A1-Part2/blob/d1c10b31ce283a24302d936c0f7e565f576a14a1/test-array.cpp#L124

https://github.com/Danijj89/CS4500-A1-Part2/blob/d1c10b31ce283a24302d936c0f7e565f576a14a1/test-array.cpp#L129

https://github.com/Danijj89/CS4500-A1-Part2/blob/d1c10b31ce283a24302d936c0f7e565f576a14a1/test-array.cpp#L142

https://github.com/Danijj89/CS4500-A1-Part2/blob/d1c10b31ce283a24302d936c0f7e565f576a14a1/test-array.cpp#L143

https://github.com/Danijj89/CS4500-A1-Part2/blob/d1c10b31ce283a24302d936c0f7e565f576a14a1/test-array.cpp#L147

**Comment by Danijj89** [comment]
Hey, the tests for the typed arrays returns the respective types. I just updated the tests. Please check them out and if there are any other issues, open a new issue. Thanks
