### ISSUE TITLE
Create default constructor

### ISSUE THREAD

**Issue by newmannj** [Danijj89/CS4500-A1-Part2#5]
Can you add a default constructor to array.h? We can determine the array type from the first element added.

**Comment by terryr1** [comment]
We agree with this. There's no need to have the type or the length in the constructor. Also we don't think it's necessary to have get_content_type()

**Comment by Danijj89** [comment]
Will add default constructor. Would removing content type altogether be good for both of you?

**Comment by Danijj89** [comment]
I added the default constructor. If you think that removing content_type would help your implementation, please open a new issue. Thanks!
