### ISSUE TITLE
Remove the partial implementation from the array class

### ISSUE THREAD

**Issue by cshelman** [Danijj89/CS4500-A1-Part2#7]
Please remove the fields in the Array class. Fields are not included in the API as implementation is up to us. Maybe even consider purging the history if you think its considered an implementation per the [FAQ](https://piazza.com/class/k51bluky59n2jr?cid=317).

**Comment by Danijj89** [comment]
Hi, the fields in array.h have been already removed in regards to a previous request. If you were referring to different fields, please open another issue. Thanks
